galaxy_info:
  author: Jon
  description: |
    A shim for the known_hosts module. Handles:
    - Looping on multiple hosts
    - Calculating the host key
  license: CC-BY-4.0

  min_ansible_version: 2.1

  platforms:
  - name: Linux
    versions:
    - all
  - name: MacOSX
    versions:
      - all


  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
